String tempImagePlaceHolder = "https://via.placeholder.com/364x120";
List<String> tempCategories = [
  "Category 1",
  "Category 2",
  "Category 3",
  "Category 4",
  "Category 1",
  "Category 2",
  "Category 3",
  "Category 4",
  "Category 1",
  "Category 2",
  "Category 3",
  "Category 4",
  "Category 1",
  "Category 2",
  "Category 3",
  "Category 4",
  "Category 1",
  "Category 2",
  "Category 3",
  "Category 4",
  "Category 1",
  "Category 2",
  "Category 3",
  "Category 4",
];
